= AME - C++ header-only DSP library for Cortex-M

image:https://github.com/AkiyukiOkayasu/ame/actions/workflows/cmake.yml/badge.svg[test] image:https://github.com/AkiyukiOkayasu/ame/actions/workflows/doxygen.yml/badge.svg[link:https://akiyukiokayasu.github.io/ame/] image:https://img.shields.io/github/v/release/AkiyukiOkayasu/ame[version] image:https://img.shields.io/github/license/AkiyukiOkayasu/ame[link=LICENSE] 

AME is a C++ header-only library focused on fast audio processing on Cortex-M, such as i.MXRT. +
Specifically, AME provides a function that is missing from the CMSIS-DSP for audio processing. +

This is my back up project and also in the early stages of the project.  +
Major changes may be added to this project. +

== Dependencies
* C++17

==== Optional
* https://arm-software.github.io/CMSIS_5/DSP/html/index.html[ARM CMSIS-DSP] +

== Feautures
* Conversion between float and Q23
* Conversion between **Decibel and Amplitude**
* Conversion between **Frequency and Period**
* Conversion between **MIDI note and Frequency**
* Interpolate functions
* Filters
* Fractional delay
* Audio buffer that can only be allocatable at compile time
* WAV reader
* Random
* White noise generator

=== TODO  
* MIDI
* Sample rate conversion

== Usage
Just copy this repository and include ame.hpp.
See the https://akiyukiokayasu.github.io/ame/[document] for details.

=== For JUCE users
ame is also a JUCE module. +
https://github.com/AkiyukiOkayasu/ame-juce[ame-juce] is a simple example of using ame as a JUCE module. +
Be aware that the order of audio samples in ame is interleaved. +
