= AME - C++ header-only DSP library for Cortex-M

AME is a C++ header-only library focused on fast audio processing on Cortex-M, such as i.MXRT. +
Specifically, AME provides a function that is missing from the CMSIS-DSP for audio processing. +

This is my back up project and also in the early stages of the project.  +
Major changes may be added to this project. +

== Dependencies
* C++17

==== Optional
* https://arm-software.github.io/CMSIS_5/DSP/html/index.html[ARM CMSIS-DSP] +

== Feautures
* Conversion between float and Q23
* Conversion between **Decibel and Amplitude**
* Conversion between **Frequency and Period**
* Conversion between **MIDI note and Frequency**
* Interpolate functions
* Filters
* Audio buffer that can only be allocatable at compile time

=== TODO  
* WAV writer/reader
* MIDI
* Sample rate conversion

== Example
https://github.com/AkiyukiOkayasu/ame-juce[ame-juce] +
An example of using ame without any hardware in combination with JUCE.

== Document
https://akiyukiokayasu.github.io/ame/[document]

== LICENSE
MIT +
link:LICENSE[LICENSE]
